import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { makeStyles, createTheme } from '@material-ui/core/styles'
import StyledButton from '../components/StyledButton'
import styles from '../styles/Home.module.css'
import TextField from '@material-ui/core/TextField'

const useStyles = makeStyles({
  root: {
    borderRadius: 3,
    color: 'white',
  },
  form: {
    marginTop: '20px',
    marginBottom: '20px',
  },
  flexdisplay: {
    display: 'flex',
    justifyContent: 'center',
  }
});

const theme = createTheme();

export default function Home() {
  const classes = useStyles();
  const [question, setQuestion] = useState('')

  const handleSubmit = (e) => {
    e.preventDefault()
    if (question) {
      console.log(question)
    }
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Giotto Tarot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Giotto Tarot</h1>
        <h2> enter your question to the cards: </h2>
        <form noValidate autoComplete="off" onSubmit={handleSubmit}>
          <TextField
            onChange={(e) => setQuestion(e.target.value)}
            fullWidth>
          </TextField>
          <StyledButton></StyledButton>
          <div className={classes.flexdisplay}>
              <p className={styles.authitem}>Log In</p> 
              <p className={styles.authitem}>||</p> 
              <p className={styles.authitem}>Sign Up</p>
          </div>
        </form>
      </main>
    </div>
  )
}
